### ISSUE TITLE
SUB1X Marketing Budget

### ISSUE THREAD

**Issue by SuB1X-Coin** [SuB1X-Coin/proposals#2]
## **Requested Funds**
100 SUB1X monthly. These funds would be paid to - `ZKYd9rPj9guYRe2HRvfVqHmJQiximoRELP`

This amounts to 23% of the total monthly governance budget. 

 ## **What is the proposal about?**
Getting a sustainable marketing budget. 

## **How is it going to help the project or the community?**
SUB1X has a lot of attractive features that other coins don't have. We have been lacking severely in the marketing department though. The biggest reason for this is because we have been operating on a shoe string budget. 

100 SUB1X monthly would give a lot of flexibility when it comes to how the funds are spent. This figure amounts to 1200 annually, which will be well under 5% of the circulating supply in a years time. 

## **What will the funds be used for?**
The funds should be distributed through a combination of paid advertising and an aggressive bounty program.

**Bounty Program**
The majority of coins will go towards fulfilling a proper bounty program. 
I'd like the coins to be spread across multiple social media platforms: Twitter, Discord, Reddit and Telegram just to name a few. 

The targeting of more crypto obscure platforms, like Instagram would be very beneficial for hosting bounties on because of how much other projects have under utilised it. 

**Articles**
CoinTelegraph and other popular crypto publications charge several thousand dollars to feature an  article in their online magazines. With the current price of SUB1X and the marketing budget I am proposing, this would not be feasible, however, the other marketing methods should be beneficial in raising awareness and thus price of the coin. When the price returns above the $50 range per coin,the fee will be paid and an effort made to get high quality promotional articles published. 

**Forum Banner Advertising**
Google has banned cryptocurrency advertising, but many online niche forums offer ways to actively promote our coin. 

**Community Manager Payments**
Another way in which the funds may end up distributed, is through the addition of monetary incentives for mods to spend more time keeping the communities of relevant platforms active. This would motivate moderators to be more active. The payments would be based on performance and would take place cyclically every few weeks. 

**Tipbot**
The integration of a tipbot into the Discord, so spontaneous contributions can be rewarded. Also, a good way to boost activity in our server. 

**The rest of the coins would go towards:**
- Masternode ranking platforms (_e.g. MasternodeDirectory charges 0.05BTC equivalent of the coin_)
- SUB1X Faucets 
- Coin Tracking (_e.g. CryptoCompare charge 0.1ETH for listing to their website_)

## **Is this your first proposal? If not, please provide links to previous proposals.**
It's my first proposal, so go easy on me...

My Discord user tag is - `willdono#3607`

**Comment by mnzone-dev** [comment]
I like the ideas presented here, but would love to see the proposal split a bit.
For example, have a separate one for the Moderators.

How is the decision of which platform to list on and for what price? Shouldn't that be a separate proposal? For example: `Proposal to list on PortalX for 30 SUB1X`. As it goes throw the draft phases maybe alternative platforms are found with better value/money ratio.

How's the accounting for these funds going to be done?

**Comment by wajito** [comment]
Sounds good. Maybe alongside a Tipbot, some for Airdrops within the Discord community as well like some other coins do?

**Comment by SuB1X-Coin** [comment]
Accounting would be kept track on a public spreadsheet for all to see. 

Reading back on it, the proposal does seem to be a bit vague. Also, 23% is quite a big chunk of the total budget, especially when there is no clear indication on the allocations for each category.

**Comment by P3shy** [comment]
A great proposal to begin with! I don't think forum banners are needed, they are not the primary source of gaining trade volume and they do bring in a few members but not a whole lot. Best thing to do is advertise the coin through the community and through word of mouth, all we need to do is an excellent job on the marketing side of things and the advertisement of SUB1X will be done naturally through the community, But loving the ideas that have been put into place so far. I do agree with you, categorizing the budget and how funds will be spent on each is crucial.

**Comment by dojo90** [comment]
1+, but there should be another poll for what it is used for.

**Comment by thewatchers1456** [comment]
Willdono please disregard my comments about this in discord. I was in unaware of how extensive the compensation distributions were.

With that being said I like the idea of these marketing funds being pulled from the governance budget. It will prevent the need for ad hoc community fundraising which can be a nightmare. In essence this would force community participation in said marketing budget requests evenly across the network. Instead of a hand full of community member footing the bill for everyone.

I like the idea.

**Comment by Klaud07** [comment]
This is a good idea, I would support it, but the expediency of all spending should be discussed by the community.

**Comment by MrsMasternode** [comment]
100 % support this and count on my MN votes for our future ... we should also be voting what the money goes to
