### ISSUE TITLE
SUB1X Premium Club + Improvement Suggestion Discussion

### ISSUE THREAD

**Issue by SuB1X-Coin** [SuB1X-Coin/proposals#5]
## Requested funds

One single 100 SUB1X payment to:
`ZMFXaQHX8Tnur2Kojp8GmA5X61JYKiJDRf`

## Describe your proposal
Discussing the idea of creating a SUB1X premium portal and suggesting any features/improvements that could be added to the blueprints for it. The top 10 most active participants on this Github issues will be given 10 coins each. 

The posts must be constructive and relevant to the utility being deliberated. 

The proposal submitted is a vote on whether coins should be rewarded to the best contributors. 

#### What is the SUB1X premium portal?
The SUB1X exclusive club provides an affordable decentralised resource centre for investors in the Masternode space. This will be done by attracting key influencers, focusing on exclusivity and creating a multi-incentive rewards based system to encourage quality content production. 

When considering a usecase for SUB1X, we wanted to consider a utility that would reflect the ultra low supply of the project and the economic principle of scarcity. The SUB1X premium portal fulfills these criteria and has many advantages over traditional content providers.    

+ **Influencers:** Each month, several influencers are given free entry into the SUB1X club. They are selected based on either credentials in the crypto/MN space or social media following. 

+ **Quality of Information:** Many groups are lacking when it comes to the availability of information. The SUB1X platform is designed to attract the most knowledgeable figures in the MN space and give monetary rewards for those who post valuable community contributions. 

+ **Dividends:** All members of the premium portal are entitled to monthly SUB1X. This will be created via a governance proposal that assigns 100 coins to a single dividends wallet. These coins are then staked and the returns are pooled together at the end of each month. 
The monthly yields depend primarily on how many members that have joined the SUB1X forum. In terms of other factors, PoS network weight would determine the amount of coins accumulated over the monthly period, but the differences would be negligible when considering the low variability in difficulty over such a short time frame. 

+ **Reward Incentive Mechanisms:** A quasi - "Proof Of Brain" consensus similar will be adopted to the algorithm used by Steemit. A minimum amount of SUB1X coins are allocated to the upvoting system, which are then distributed to members based on a variety of factors: reputation ranking, post popularity and  

There are 2 potential ways to generate and distribute coins to existing premium portal users. 

1) _Governance Budget:_ Send a proposal to the blockchain that MN holders can vote on. A budget would be determined and these coins would then be allocated to users based on the amount of upvoting power they have. This would take place periodically on either a weekly, or monthly basis via a script.  

2) _Block Rewards:_ One would be to dedicate an existing % of the current 0.05BR towards the premium portal. Once again the proportion would have to be decided by governance vote, but would most likely range between 10 - 20%. These coins would be pooled together at one address and allocated through a script. Alternatively, the total BR could be increased by 0.005 - 0.01 SUB1X. 
 
+ **No Spam:** Forums are prone for falling victim to spam. It can be a pain to sift through such content and difficult to deal with for site administrators. The selective and exclusive nature of the SUB1X premium club, means that it will not suffer from any of these issues. The fee of purchasing a MasterNode would create a suitable deterrent for mitigating any low level shill/spam posts. 

## How is it going to help the project or the community?
To move forward, the coin requires a viable use case. A Github issue is the perfect way to discuss the potential implications, drawbacks and suggestions for the SUB1X premium club.  

## What will the funds be used for?
Is this your first proposal? If not, please provide links to previous proposals.

Marketing #2 
Bounty Program #4  
 
## Proposal creator Discord user
willdono

**Comment by thewatchers1456** [comment]
I think this would be an amazing utility for the coin.
I do have a few suggestions that may contribute to the long term success of the SUB1X Premium Portal project. 

1) If the SUB1X Premium Portal requires a one time fee or a time based subscription in SUB1X I believe that these fees would be best used in the dividend distributions. 
     - I personally believe that any subscription fees collected should be evenly and fairly distributed amongst all active member of the premium portal for the collection/distribution period. (Active Members is defined as and active poster of content/information or an active voter of others content)
     - (One Time Membership Fee) Top influencers in the MN/Crypto realm may have fees reduced or waved like you said in the above post to encourage adoption and use of the platform. 
    - (Time Based Subscription) Top influencers in the MN/Crypto realm may have fees temporary reduced or waved for a set amount of time to encourage adoption and use of the platform. 
    - The number of Top Influencers in the MN/Crypto realm that can be given reduced or waved fees should be capped to no more than XX per month. By restricting the number of free or reduced admission it will encourage more to buy off the market so that they can join. 



2) If Joining the SUB1X Premium Portal does not require a fee and anyone can join I would recommend a minimum deposit balance be imposed to be authorized to post content and Up-Vote other posters content. This will do a few things.
     - By removing the restrictions for joining the platform it will encourage adoption so that member can follow their favorite influencers.
     - By restricting users from being able to post till they hold the minimum balance it will prevent excessive spamming and shilling on the platform. 
     - By restricting users from being able to Up-Vote posted content till they hold the minimum balance it will prevent any gaming of the voting system by users Up-Voting their own content using many different accounts managed by bots. This will keep the Up-Voting system fare and strictly wallet weight based.
     - By removing the ability to Post and Up-Vote content, users that are under the minimum deposit balance will not be classified as "Active Members" and will not be authorized to take part in any Dividend Distributions. 



3) Dividend Staking Solutions 
     - With the requirement for users to deposit a minimum amount of SUB1X into their SUB1X Premium Portal account's wallet address to post and up-vote. It gives the ability for the Portal's Wallet.dat to not only stake the 100 coins from this proposal, but also all of the coins deposited in all the accounts.  



4) Up-Vote weight should be tied to how many SUB1X coins the users has in their SUB1X Premium Portal wallet as long as it is over the minimum deposit limit.

**Comment by Thatdudesbro** [comment]
TheWatchers and I spoke in great length on the phone regarding this use case of the Sub1x coin, and I feel it would be irresponsible of me not to share those topics here.

First, I do agree that this project would be an excellent introductory use case that would at the bare minimum stabilize the market value - if not further the value of the coin.

What we need to keep in mind, is that the portal must be cost effective to the user. Meaning the "subscription cost" should not out-weigh the benefit of the forum. SPAM and FUD are detrimental to a forums environment. having to comb through thousands of GIFs and When Moon / When Exchange comments to find pertinent information is not only inconvenient, but annoying to the user. Subscription cost alone may be enough to keep this behavior at bay. But to go a little further, you could charge by the character or k byte to post. this could substantially reduce the likelihood of spam, while a reward structure could be developed to provide incentive for posting valuable information (Up-Voting.)

A tiered subscription structure could be useful as well; were you could unlock features such as:

Tier 1. Viewing Thread | Voting | Re-posting | Posting of original content
Tier 2. Viewing Thread | Voting | Re-posting
Tier 3. Viewing Thread | Voting
Tier 4. Viewing Thread

One last note... for now anyway.
The portal should be accessible through the Sub1x wallet, giving the user the ability to:
- view the most recent post
- pay any subscription costs
- upgrade subscription tier level
- launch the forum web page or UI

**Comment by thewatchers1456** [comment]
ThatDudesBro,

Although it would be amazing to have access to the Protal from inside the wallet I dont know if it would be possible unless you link your wallet to the Portal account. But it a very interesting concept!

Thinking about it now the wallet may be able to have a tab added to that has a Portal login prompt, but I would worry about security of the funds in your wallet. If you can open a pipe from your wallet to the portal then a pipe may be be possible from your portal account to your wallet. That makes me nervous. 

In regards to the tiered access I really like the idea! But I personally do not like needing to pay a fee or a subscription to access the portal. Unless any subscription fees are returned to all Active Members. In my opinion there needs to be an incentive with zero drawbacks to paying a fee to access. Say that there is a monthly subscription fee of 1 SUB1X to access the portal. Active Members (users that make a post, re-post, or vote) in my opinion should have that fee saved. The only time I think a user should have to top off their account is if they do not remain active for the subscription time. 

But this is only if there is a subscription fee.

I honestly think it would lead to long term success of the portal if we change the tiered fee structure to a tiered minimum deposit.

Tier 1: 2 SUB1X (View Portal)
Tier 2: 4 SUB1X (View Portal, Up-Vote)
Tier 3: 8 SUB1X (View Portal, Up-Vote, Re-Post)
Tier 4: 16 SUB1X (View Portal, Up-vote, Re-post, Post original content)

The reason I like having the minimum deposit to access and use the site is it will give the sites wallet.dat even more than the 100 coins to staking. Having more coins staking for portal rewards will prevent the need to create future proposals for rewards. 

As more portal users come online the. We can have governance proposals to increase the amount of SUB1X in the voting pool.

**Comment by Thatdudesbro** [comment]
Locking the "deposit" into an input address associated with the user's portal account would reinforce the idea of "The more you put in - the more you get out" by increasing the staking power of the input as you apply for a higher tier level. Plus we don't want people opening an account only to withdraw the assets again. This should disable the account or reduce the account access to tier 0.

Would the posts be transmitted using the block chain?
This could possibly be accomplished using the multi-send function and sending thread posts to all locked portal input addresses. I specified locked inputs because it is my understanding that every staking reward distributed creates a new input.

**Comment by SuB1X-Coin** [comment]
The posts would not be transmitted using the blockchain and the forum itself would be offchain. However, the upvoting system, relies entirely on the governance proposal budgets.

**Comment by ghost** [comment]
closing this as the proposal as been voted and paid
